project:
  type: book
  output-dir: docs

book:
  title: "Categories for the Curious"
  subtitle: "A Light Intro to Category Theory"
  author: "John Cavanaugh"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - sets.qmd
    - posets.qmd
    - groups.qmd
    - vectorSpaces.qmd
    - abstractCategories.qmd
    - functors.qmd
    - naturalTransformations.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc-depth: 4
  pdf:
    toc: true
    number-sections: true
    documentclass: scrreprt
