project:
  type: book
  output-dir: docs

book:
  title: "Categories for the Curious"
  subtitle: "A Light Intro to Category Theory"
  author: "John Cavanaugh"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - posets.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc-depth: 4
  pdf:
    toc: true
    number-sections: true
    documentclass: scrreprt

theorem:
  exercise:
    name: Exercise
    counter: exdef

  definition:
    name: Definition
    counter: exdef
